# config partagee (non sensible)
# les secrets (cle TMDB, mdp postgres) sont dans secret.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cinescope-config
  namespace: cinescope
data:
  ENV: "production"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "cinescope"
  DB_USER: "cinescope"
